import { CardInformationType } from "@/types/gameTypes";
import { cropsSvg } from "./images";

export const cardData: CardInformationType[] = [
  {
    id: 0,
    name: "pepperoni",
    totalQuantity: 6,
    value: [2, null, 4, null],
    svg: cropsSvg.pepperoni,
  },
  {
    id: 1,
    name: "peas",
    totalQuantity: 7,
    value: [2, 3, 5, null],
    svg: cropsSvg.peas,
  },
  {
    id: 2,
    name: "eggplant",
    totalQuantity: 8,
    value: [2, 4, 5, null],
    svg: cropsSvg.eggplant,
  },
  {
    id: 3,
    name: "tomato",
    totalQuantity: 9,
    value: [2, 4, 6, null],
    svg: cropsSvg.tomato,
  },
  {
    id: 4,
    name: "melon",
    totalQuantity: 10,
    value: [3, 4, 5, 7],
    svg: cropsSvg.melon,
  },
  {
    id: 5,
    name: "corn",
    totalQuantity: 11,
    value: [3, 5, 6, 7],
    svg: cropsSvg.corn,
  },
  {
    id: 6,
    name: "pumpkin",
    totalQuantity: 12,
    value: [3, 5, 6, 8],
    svg: cropsSvg.pumpkin,
  },
  {
    id: 7,
    name: "turnip",
    totalQuantity: 13,
    value: [3, 5, 7, 8],
    svg: cropsSvg.turnip,
  },
  {
    id: 8,
    name: "carrot",
    totalQuantity: 14,
    value: [4, 5, 7, 8],
    svg: cropsSvg.carrot,
  },
  {
    id: 9,
    name: "beans",
    totalQuantity: 15,
    value: [4, 6, 7, 8],
    svg: cropsSvg.beans,
  },
  {
    id: 10,
    name: "onion",
    totalQuantity: 16,
    value: [4, 6, 7, 9],
    svg: cropsSvg.onion,
  },
  {
    id: 11,
    name: "potato",
    totalQuantity: 17,
    value: [4, 6, 8, 9],
    svg: cropsSvg.potato,
  },
  {
    id: 12,
    name: "cucumber",
    totalQuantity: 18,
    value: [4, 6, 8, 10],
    svg: cropsSvg.cucumber,
  },
];
